=== Team302/2020InfiniteRecharge/src/main/autonxml/auton.dtd
<!ELEMENT auton (primitive*) >

<!-- primitive IDs

       enum PRIMITIVE_IDENTIFIER
         {
             UNKNOWN_PRIMITIVE = -1,
             DO_NOTHING,
             HOLD_POSITION,
             DRIVE_DISTANCE,
             DRIVE_TIME,
             DRIVE_TO_CUBE,
             TURN_ANGLE_ABS,
             TURN_ANGLE_REL,
			 DRIVE_TO_WALL,
			 TURN_TO_CUBE,
			 DRIVE_LIDAR_DISTANCE,
             MAX_AUTON_PRIMITIVES
         };
			
		time in seconds
		distance in inches
		heading in degrees	
		drivespeed in inches per second
			

		enum LIFT_PRESET_HEIGHTS
		{
			KEEP_SAME = -1,
			FLOOR,
			SWITCH,
			SCALE
		};

-->

<!ELEMENT primitive EMPTY >
<!ATTLIST primitive 
          id                ( DO_NOTHING | HOLD_POSITION | 
                              DRIVE_DISTANCE | DRIVE_TIME | DRIVE_TO_WALL | 
                              TURN_ANGLE_ABS | TURN_ANGLE_REL | AUTO_SHOOT ) "DO_NOTHING"
		  time				CDATA #IMPLIED
          distance		    CDATA "0.0"
          heading           CDATA "0.0"
          drivespeed        CDATA "0.0"
          enddrivespeed     CDATA "0.0"
          xloc				CDATA "0.0"
          yloc				CDATA "0.0"
          ballState         ( OFF | INTAKE | INTAKE_HUMAN_PLAYER | HOLD | GET_READY_TO_SHOOT | SHOOT | TURRET_TURN_ANGLE ) "OFF"
          turretAngle       CDATA #IMPLIED
>

=== Team302/2020InfiniteRecharge/src/main/autonxml/tobetested/trrenchrunsteal.xml
<?xml version="1.0"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>
	<primitive id="DRIVE_DISTANCE"
			   distance="140.0"
			   drivespeed="60.0"               
               ballState="INTAKE"
               turretAngle="0.0"/>
	<primitive id="DRIVE_DISTANCE"
			   distance="-49.0"
			   drivespeed="60.0"               
               ballState="GET_READY_TO_SHOOT"
               turretAngle="0.0"/>
	<primitive id="TURN_ANGLE_REL"
			   heading="-90.0"
               ballState="GET_READY_TO_SHOOT"/>
	<primitive id="DRIVE_DISTANCE"
			   distance="113.0"
			   drivespeed="60.0"
               ballState="GET_READY_TO_SHOOT"
               turretAngle="180.0"/>
	<primitive id="HOLD_POSITION"
			   time="0.25"
               ballState="SHOOT"/>
	<primitive id="TURN_ANGLE_REL"
			   heading="15.0"
               ballState="INTAKE"/>
	<primitive id="DRIVE_DISTANCE"
			   distance="130.0"
			   drivespeed="60.0"
               ballState="GET_READY_TO_SHOOT"
               turretAngle="0.0"/>
	<primitive id="HOLD_POSITION"
			   time="0.25"
               ballState="SHOOT"/>
</auton>
